# Generated by Django 5.2 on 2025-05-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_service"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainer",
            options={
                "ordering": (
                    "user__last_name",
                    "user__first_name",
                    "user__middle_name",
                ),
                "verbose_name": "Тренер",
                "verbose_name_plural": "Тренеры",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="max_participants",
            field=models.PositiveIntegerField(default=10, verbose_name="Кол-во мест"),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.DurationField(
                help_text="Укажите продолжительность в секундах или в формате 'ЧЧ:ММ:СС'",
                verbose_name="Продолжительность",
            ),
        ),
    ]
