# Generated by Django 5.2 on 2025-07-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_trainer_options_service_max_participants_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="specialization",
            field=models.TextField(verbose_name="Специализация"),
        ),
    ]
