# Generated by Django 5.2 on 2025-07-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_trainer_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="color",
            field=models.CharField(
                default="#6c757d", max_length=7, verbose_name="Цвет"
            ),
        ),
    ]
