# Generated by Django 5.2 on 2025-12-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_service_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="achievements",
            field=models.TextField(blank=True, default="", verbose_name="Достижения"),
        ),
    ]
