# Generated by Django 5.2 on 2025-05-09 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_birth_date_user_middle_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Телефон должен быть в формате '+7 (777) 777 77-77'",
                        regex="^\\+7 \\(\\d{3}\\) \\d{3} \\d{2}-\\d{2}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
