# Generated by Django 5.2 on 2025-05-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("М", "Мужской"), ("Ж", "Женский")],
                max_length=1,
                null=True,
                verbose_name="Пол",
            ),
        ),
    ]
