# Generated by Django 5.2 on 2025-12-11 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0005_user_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("", "Не указано"), ("М", "Мужской"), ("Ж", "Женский")],
                default="",
                max_length=1,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, default="", verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=18,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Телефон должен быть в формате '+7 (777) 777 77-77'",
                        regex="^\\+7 \\(\\d{3}\\) \\d{3} \\d{2}-\\d{2}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_number", ""), _negated=True),
                fields=("phone_number",),
                name="unique_nonempty_phone_number",
            ),
        ),
    ]
