# Generated by Django 5.2 on 2025-12-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_options_alter_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "Пользователь с таким адресом электронной почты уже существует."
                },
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
