# Generated by Django 5.2 on 2025-12-17 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0008_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "Пользователь с таким адресом электронной почты уже существует"
                },
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="",
                error_messages={
                    "unique": "Пользователь с таким номером телефона уже существует"
                },
                max_length=18,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Телефон должен быть в формате '+7 (777) 777-77-77'",
                        regex="^\\+7 \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterConstraint(
            model_name="user",
            name="unique_nonempty_phone_number",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_number", ""), _negated=True),
                fields=("phone_number",),
                name="unique_nonempty_phone_number",
                violation_error_message="Пользователь с таким номером телефона уже существует",
            ),
        ),
    ]
