# Generated by Django 5.2 on 2025-06-01 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_trainer_options_service_max_participants_and_more"),
        ("schedule", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "ordering": (
                    "start_time",
                    "service__name",
                    "trainer__user__last_name",
                    "trainer__user__first_name",
                    "trainer__user__middle_name",
                ),
                "verbose_name": "Расписание",
                "verbose_name_plural": "Расписание",
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking",
                to="schedule.schedule",
                verbose_name="Занятие",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("schedule", "client")},
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={("trainer", "start_time")},
        ),
    ]
